export const API_BASE_URL = 'http://localhost:3001/api'
export const WS_BASE_URL = 'ws://localhost:3001'
export const MEDIA_BASE_URL = 'http://localhost:3001'
export const APP_NAME = '拾光引擎AI'
export const APP_VERSION = '1.0.0'
